import type { League } from "./types"

export const mockLeagues: League[] = [
  {
    id: "1",
    name: "NHL",
    games: [
      {
        id: "1",
        homeTeam: {
          id: "h1",
          name: "Boston Bruins",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/45724.png",
          players: [
            { number: "37", name: "Patrice Bergeron" },
            { number: "63", name: "Brad Marchand" },
            { number: "88", name: "David Pastrnak" },
            { number: "73", name: "Charlie McAvoy" },
            { number: "40", name: "Tuukka Rask" },
            { number: "46", name: "David Krejci" },
            { number: "74", name: "Jake DeBrusk" },
            { number: "25", name: "Brandon Carlo" },
            { number: "55", name: "Jeremy Lauzon" },
            { number: "10", name: "Anders Bjork" },
          ],
        },
        awayTeam: {
          id: "a1",
          name: "Toronto Maple Leafs",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/48256.png",
          players: [
            { number: "34", name: "Auston Matthews" },
            { number: "16", name: "Mitch Marner" },
            { number: "91", name: "John Tavares" },
            { number: "88", name: "William Nylander" },
            { number: "44", name: "Morgan Rielly" },
            { number: "36", name: "Jack Campbell" },
            { number: "24", name: "Wayne Simmonds" },
            { number: "15", name: "Alex Kerfoot" },
            { number: "94", name: "Tyson Barrie" },
            { number: "3", name: "Justin Holl" },
          ],
        },
        date: "2025-01-15",
        time: "19:00",
        venue: "TD Garden",
      },
      {
        id: "2",
        homeTeam: {
          id: "h2",
          name: "Montreal Canadiens",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/45724.png",
          players: [
            { number: "22", name: "Cole Caufield" },
            { number: "14", name: "Nick Suzuki" },
            { number: "77", name: "Kirby Dach" },
            { number: "62", name: "Artturi Lehkonen" },
            { number: "26", name: "Jeff Petry" },
            { number: "31", name: "Carey Price" },
            { number: "17", name: "Josh Anderson" },
            { number: "94", name: "Corey Perry" },
            { number: "8", name: "Ben Chiarot" },
            { number: "21", name: "Eric Staal" },
          ],
        },
        awayTeam: {
          id: "a2",
          name: "Ottawa Senators",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/48256.png",
          players: [
            { number: "7", name: "Brady Tkachuk" },
            { number: "19", name: "Drake Batherson" },
            { number: "9", name: "Josh Norris" },
            { number: "28", name: "Connor Brown" },
            { number: "72", name: "Thomas Chabot" },
            { number: "30", name: "Matt Murray" },
            { number: "18", name: "Tim Stutzle" },
            { number: "44", name: "Erik Brannstrom" },
            { number: "21", name: "Nick Paul" },
            { number: "14", name: "Austin Watson" },
          ],
        },
        date: "2025-01-15",
        time: "19:30",
        venue: "Bell Centre",
      },
      {
        id: "5",
        homeTeam: {
          id: "h5",
          name: "New York Rangers",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/45724.png",
          players: [
            { number: "10", name: "Artemi Panarin" },
            { number: "93", name: "Mika Zibanejad" },
            { number: "20", name: "Chris Kreider" },
            { number: "23", name: "Adam Fox" },
            { number: "31", name: "Igor Shesterkin" },
            { number: "55", name: "Ryan Lindgren" },
            { number: "16", name: "Vincent Trocheck" },
            { number: "72", name: "Filip Chytil" },
            { number: "13", name: "Alexis Lafreniere" },
            { number: "79", name: "K'Andre Miller" },
          ],
        },
        awayTeam: {
          id: "a5",
          name: "Pittsburgh Penguins",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/48256.png",
          players: [
            { number: "87", name: "Sidney Crosby" },
            { number: "71", name: "Evgeni Malkin" },
            { number: "59", name: "Jake Guentzel" },
            { number: "58", name: "Kris Letang" },
            { number: "17", name: "Bryan Rust" },
            { number: "30", name: "Matt Murray" },
            { number: "12", name: "Zach Aston-Reese" },
            { number: "19", name: "Jared McCann" },
            { number: "6", name: "John Marino" },
            { number: "77", name: "Jeff Carter" },
          ],
        },
        date: "2024-12-20",
        time: "19:00",
        venue: "Madison Square Garden",
      },
      {
        id: "6",
        homeTeam: {
          id: "h6",
          name: "Chicago Blackhawks",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/45724.png",
          players: [
            { number: "88", name: "Patrick Kane" },
            { number: "19", name: "Jonathan Toews" },
            { number: "12", name: "Alex DeBrincat" },
            { number: "77", name: "Kirby Dach" },
            { number: "2", name: "Duncan Keith" },
            { number: "50", name: "Corey Crawford" },
            { number: "64", name: "David Kampf" },
            { number: "44", name: "Calvin de Haan" },
            { number: "7", name: "Brent Seabrook" },
            { number: "14", name: "Boris Katchouk" },
          ],
        },
        awayTeam: {
          id: "a6",
          name: "Detroit Red Wings",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/48256.png",
          players: [
            { number: "71", name: "Dylan Larkin" },
            { number: "39", name: "Anthony Mantha" },
            { number: "14", name: "Robby Fabbri" },
            { number: "59", name: "Tyler Bertuzzi" },
            { number: "53", name: "Moritz Seider" },
            { number: "35", name: "Ville Husso" },
            { number: "23", name: "Lucas Raymond" },
            { number: "17", name: "Daniel Sprong" },
            { number: "73", name: "Adam Erne" },
            { number: "21", name: "Mitchell Stephens" },
          ],
        },
        date: "2024-11-10",
        time: "20:00",
        venue: "United Center",
      },
      {
        id: "7",
        homeTeam: {
          id: "h7",
          name: "Tampa Bay Lightning",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/45724.png",
          players: [
            { number: "91", name: "Steven Stamkos" },
            { number: "86", name: "Nikita Kucherov" },
            { number: "21", name: "Brayden Point" },
            { number: "77", name: "Victor Hedman" },
            { number: "88", name: "Andrei Vasilevskiy" },
            { number: "9", name: "Tyler Johnson" },
            { number: "18", name: "Ondrej Palat" },
            { number: "27", name: "Ryan McDonagh" },
            { number: "71", name: "Anthony Cirelli" },
            { number: "14", name: "Pat Maroon" },
          ],
        },
        awayTeam: {
          id: "a7",
          name: "Florida Panthers",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/48256.png",
          players: [
            { number: "16", name: "Aleksander Barkov" },
            { number: "72", name: "Sergei Bobrovsky" },
            { number: "23", name: "Carter Verhaeghe" },
            { number: "11", name: "Jonathan Huberdeau" },
            { number: "5", name: "Aaron Ekblad" },
            { number: "13", name: "Sam Reinhart" },
            { number: "74", name: "Owen Tippett" },
            { number: "77", name: "Frank Vatrano" },
            { number: "52", name: "MacKenzie Weegar" },
            { number: "19", name: "Mason Marchment" },
          ],
        },
        date: "2025-01-20",
        time: "19:30",
        venue: "Amalie Arena",
      },
    ],
  },
  {
    id: "2",
    name: "SHL",
    games: [
      {
        id: "3",
        homeTeam: {
          id: "h3",
          name: "Frölunda HC",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/45724.png",
          players: [
            { number: "91", name: "Ryan Lasch" },
            { number: "19", name: "Pontus Holmberg" },
            { number: "28", name: "Elmer Soderblom" },
            { number: "44", name: "Max Friberg" },
            { number: "7", name: "Henrik Tommernes" },
            { number: "35", name: "Lars Johansson" },
            { number: "10", name: "Johan Sundstrom" },
            { number: "23", name: "Simon Hjalmarsson" },
            { number: "4", name: "Mattias Norstebo" },
            { number: "15", name: "Mats Rosseli Olsen" },
          ],
        },
        awayTeam: {
          id: "a3",
          name: "Djurgårdens IF",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/48256.png",
          players: [
            { number: "29", name: "Jacob Josefson" },
            { number: "77", name: "Linus Klasen" },
            { number: "61", name: "Sebastian Strandberg" },
            { number: "8", name: "Marcus Sorensen" },
            { number: "55", name: "Philip Holm" },
            { number: "40", name: "Niklas Svedberg" },
            { number: "18", name: "Patrik Berglund" },
            { number: "24", name: "Jesper Sellgren" },
            { number: "14", name: "Emil Bemstrom" },
            { number: "6", name: "Olle Alsing" },
          ],
        },
        date: "2025-01-16",
        time: "18:00",
        venue: "Scandinavium",
      },
      {
        id: "8",
        homeTeam: {
          id: "h8",
          name: "Luleå HF",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/45724.png",
          players: [
            { number: "91", name: "Einar Emanuelsson" },
            { number: "19", name: "Isac Brännström" },
            { number: "28", name: "Jack Connolly" },
            { number: "44", name: "Nils Lundkvist" },
            { number: "7", name: "Joel Lassinantti" },
            { number: "35", name: "Jesper Wallstedt" },
            { number: "10", name: "Petter Emanuelsson" },
            { number: "23", name: "Konstantin Komarek" },
            { number: "4", name: "Erik Gustafsson" },
            { number: "15", name: "Oscar Möller" },
          ],
        },
        awayTeam: {
          id: "a8",
          name: "Skellefteå AIK",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/48256.png",
          players: [
            { number: "29", name: "Andreas Wingerli" },
            { number: "77", name: "Jonathan Pudas" },
            { number: "61", name: "Linus Karlsson" },
            { number: "8", name: "Jesper Frödén" },
            { number: "55", name: "Albin Sundsvik" },
            { number: "40", name: "Gustaf Lindvall" },
            { number: "18", name: "Rickard Hugg" },
            { number: "24", name: "Adam Wilsby" },
            { number: "14", name: "Melker Karlsson" },
            { number: "6", name: "Jonathan Johnson" },
          ],
        },
        date: "2024-12-01",
        time: "17:00",
        venue: "Coop Norrbotten Arena",
      },
    ],
  },
  {
    id: "3",
    name: "KHL",
    games: [
      {
        id: "4",
        homeTeam: {
          id: "h4",
          name: "SKA Saint Petersburg",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/45724.png",
          players: [
            { number: "17", name: "Andrei Kuzmenko" },
            { number: "19", name: "Jori Lehtera" },
            { number: "97", name: "Nikita Gusev" },
            { number: "12", name: "Miro Aaltonen" },
            { number: "77", name: "Anton Belov" },
            { number: "83", name: "Magnus Hellberg" },
            { number: "27", name: "Vladislav Gavrikov" },
            { number: "55", name: "Bogdan Kiselevich" },
            { number: "10", name: "Sergei Plotnikov" },
            { number: "71", name: "Evgeni Malkin" },
          ],
        },
        awayTeam: {
          id: "a4",
          name: "CSKA Moscow",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/48256.png",
          players: [
            { number: "13", name: "Pavel Datsyuk" },
            { number: "97", name: "Kirill Kaprizov" },
            { number: "71", name: "Konstantin Okulov" },
            { number: "19", name: "Mikhail Grigorenko" },
            { number: "44", name: "Nikita Nesterov" },
            { number: "90", name: "Ilya Sorokin" },
            { number: "25", name: "Linden Vey" },
            { number: "5", name: "Bogdan Kiselevich" },
            { number: "17", name: "Anton Slepyshev" },
            { number: "8", name: "Mat Robinson" },
          ],
        },
        date: "2025-01-17",
        time: "19:30",
        venue: "Ice Palace",
      },
      {
        id: "9",
        homeTeam: {
          id: "h9",
          name: "Dynamo Moscow",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/45724.png",
          players: [
            { number: "17", name: "Vadim Shipachyov" },
            { number: "19", name: "Dmitri Jaskin" },
            { number: "97", name: "Oscar Lindberg" },
            { number: "12", name: "Andrei Mironov" },
            { number: "77", name: "Daniil Tarasov" },
            { number: "83", name: "Alexander Yeryomenko" },
            { number: "27", name: "Eric O'Dell" },
            { number: "55", name: "Yegor Zaitsev" },
            { number: "10", name: "Rob Klinkhammer" },
            { number: "71", name: "Juuso Hietanen" },
          ],
        },
        awayTeam: {
          id: "a9",
          name: "Ak Bars Kazan",
          icon: "https://bluemountaincougars.nl/bmc-content/team-icons/48256.png",
          players: [
            { number: "13", name: "Dmitri Voronkov" },
            { number: "97", name: "Artyom Galimov" },
            { number: "71", name: "Stanislav Galiyev" },
            { number: "19", name: "Stephane Da Costa" },
            { number: "44", name: "Albert Yarullin" },
            { number: "90", name: "Timur Bilyalov" },
            { number: "25", name: "Dmitri Katelevsky" },
            { number: "5", name: "Patrice Cormier" },
            { number: "17", name: "Kirill Petrov" },
            { number: "8", name: "Viktor Tikhonov" },
          ],
        },
        date: "2025-01-25",
        time: "18:00",
        venue: "VTB Ice Palace",
      },
    ],
  },
]

export const penaltyTypes = [
  "Tripping",
  "Hooking",
  "Slashing",
  "Holding",
  "Interference",
  "High-sticking",
  "Roughing",
  "Cross-checking",
  "Boarding",
  "Charging",
  "Elbowing",
  "Delay of Game",
  "Too Many Men",
  "Unsportsmanlike Conduct",
  "Fighting",
]

export const goalSituations = [
  { value: "EV", label: "Even Strength" },
  { value: "PP", label: "Power Play" },
  { value: "SH", label: "Short Handed" },
  { value: "EN", label: "Empty Net" },
  { value: "PS", label: "Penalty Shot" },
]

export const goalTypes = ["Wrist", "Slap", "Snap", "Backhand", "Deflection", "Tip", "Wrap"]

export const mockGames = mockLeagues.flatMap((league) => league.games)
